### ISSUE TITLE
[Continue-Scaling-Plan] Testing jSnapLoader

### ISSUE THREAD

**Issue by pavly-gerges** [Electrostat-Lab/jSnapLoader#21]
## Testing: 
- [x] Evaluation for memory leaks.
- [x] Re-evaluation of the library on the non-common platforms (Linux-arm).

**Comment by stephengold** [comment]
Linux-arm testing progress:
1. The new v0.4.1 release of [the jolt-jni library](https://github.com/stephengold/jolt-jni) includes native libraries for arm-linux (32-bit) and aarch64-linux (64-bit) platforms.
2. [The snap-jolt project](https://github.com/stephengold/snap-jolt) builds on aarch64-linux. Each build runs the "HelloWorld.java" app, which extracts and loads a jolt-jni native library using jSnapLoader v1.0.0-delta. So I am confident jSnapLoader works on aarch64-linux.

Testing on arm-linux is proving difficult because my Raspberry Pi 400's "libstdc++.so" is a bit too old for jolt-jni.

**Comment by pavly-gerges** [comment]
> Testing on arm-linux is proving difficult because my Raspberry Pi 400's "libstdc++.so" is a bit too old for jolt-jni.

Have you tried updating the G++ Toolchains? Yeah, compare versions and try to update the g++. I see a new issue on Jolt-Physics regarding Linux-arm, but yeah, let me know how it goes.

**Comment by pavly-gerges** [comment]
> Linux-arm testing progress:
> 
> 1. The new v0.4.1 release of [the jolt-jni library](https://github.com/stephengold/jolt-jni) includes native libraries for arm-linux (32-bit) and aarch64-linux (64-bit) platforms.
> 2. [The snap-jolt project](https://github.com/stephengold/snap-jolt) builds on aarch64-linux. Each build runs the "HelloWorld.java" app, which extracts and loads a jolt-jni native library using jSnapLoader v1.0.0-delta. So I am confident jSnapLoader works on aarch64-linux.

Thanks for your comprehensive testing. I believe we can proceed for a stable release.

**Comment by pavly-gerges** [comment]
I first need to prepare an Android test example, that will not take much time hopefully.
EDIT:
Okay, never mind, there is another issue for this.

**Comment by pavly-gerges** [comment]
First round for evaluation for memory leaks has been completed using `jconsole`, `GNOME System Monitor`, and `JUL (Java Util Logger) API`. The new PR concludes some maneuvers to handle potential memory leaks resulting from the unclosure of resource streams especially when failure events are dispatched, namely _file localization failures_, and _file extraction failures_.
